//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BaseDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Clientes
    {
        public decimal numerador { get; set; }
        public string codcliente { get; set; }
        public string nombrecliente { get; set; }
        public string direcioncliente { get; set; }
        public string localidacliente { get; set; }
        public string cod_postalcliente { get; set; }
        public string provinciacliente { get; set; }
        public string cifcliente { get; set; }
        public string grupocliente { get; set; }
        public string telefonocliente { get; set; }
        public string faxcliente { get; set; }
        public string movilcliente { get; set; }
        public string contactocliente { get; set; }
        public string mailcliente { get; set; }
        public string comentariocliente { get; set; }
        public string activocliente { get; set; }
        public decimal tarifacliente { get; set; }
        public string recargo { get; set; }
        public Nullable<decimal> iban1cliente { get; set; }
        public Nullable<decimal> iban2cliente { get; set; }
        public Nullable<decimal> iban3cliente { get; set; }
        public decimal iban4cliente { get; set; }
        public Nullable<decimal> iban5cliente { get; set; }
        public Nullable<decimal> iban6cliente { get; set; }
        public string domiciliadocliente { get; set; }
        public string avioncliente { get; set; }
        public string mod100 { get; set; }
        public string mod111 { get; set; }
        public string mod115 { get; set; }
        public string mod123 { get; set; }
        public string mod130 { get; set; }
        public string mod131 { get; set; }
        public string mod180 { get; set; }
        public string mod190 { get; set; }
        public string mod193 { get; set; }
        public string mod200 { get; set; }
        public string mod202 { get; set; }
        public string mod303 { get; set; }
        public string mod309 { get; set; }
        public string mod349 { get; set; }
        public string mod390 { get; set; }
        public string mod751 { get; set; }
        public string mod752 { get; set; }
        public string instrastatcliente { get; set; }
        public string altacliente { get; set; }
        public string bajacliente { get; set; }
        public Nullable<System.DateTime> fechaaltacliente { get; set; }
        public Nullable<decimal> empleadoscliente { get; set; }
    }
}
