//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BaseDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cuentas
    {
        public string numerador { get; set; }
        public string digitos { get; set; }
        public string ctacliente { get; set; }
        public string ctabanco { get; set; }
        public string ctasuplidos { get; set; }
        public string ctaretenciones { get; set; }
        public string ctaprestaciones { get; set; }
        public string ctaiva0 { get; set; }
        public string ctaivasuperreducido { get; set; }
        public string ctaivareducido { get; set; }
        public string ctaivageneral { get; set; }
        public string rutasubcuenta { get; set; }
        public string rutadiario { get; set; }
        public string rutaasi { get; set; }
        public string rutacsb19 { get; set; }
    }
}
