//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BaseDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cuentas
    {
        public decimal cod { get; set; }
        public Nullable<decimal> CtaCliente { get; set; }
        public Nullable<decimal> CtaBanco { get; set; }
        public Nullable<decimal> CtaSuplido { get; set; }
        public Nullable<decimal> CtaRetencion { get; set; }
        public Nullable<decimal> CtaPrestaciones { get; set; }
        public Nullable<decimal> Iva0 { get; set; }
        public Nullable<decimal> IvaSuper { get; set; }
        public Nullable<decimal> IvaReducido { get; set; }
        public Nullable<decimal> IvaGeneral { get; set; }
        public string RutaSubcuenta { get; set; }
        public string RutaDiario { get; set; }
        public string RutaAsi { get; set; }
        public string RutaCSB19 { get; set; }
        public string NumDigitos { get; set; }
    }
}
