//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BaseDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Facturas
    {
        public decimal factcontador { get; set; }
        public Nullable<decimal> factnumerofact { get; set; }
        public string factremesa { get; set; }
        public string factfecha { get; set; }
        public Nullable<decimal> factcodcliente { get; set; }
        public string factnombre { get; set; }
        public string factdireccion { get; set; }
        public string factlocalidad { get; set; }
        public string factprovincia { get; set; }
        public string factcp { get; set; }
        public string factnif { get; set; }
        public string factiban1 { get; set; }
        public Nullable<decimal> factiban2 { get; set; }
        public Nullable<decimal> factiban3 { get; set; }
        public Nullable<decimal> factiban4 { get; set; }
        public Nullable<decimal> factiban5 { get; set; }
        public Nullable<decimal> factiban6 { get; set; }
        public string factconcepto1 { get; set; }
        public Nullable<decimal> factbase1 { get; set; }
        public string factconcepto2 { get; set; }
        public Nullable<decimal> factbase2 { get; set; }
        public Nullable<decimal> factemleados { get; set; }
        public Nullable<decimal> factprecioempleado { get; set; }
        public Nullable<decimal> factbaseempleado { get; set; }
        public Nullable<decimal> facttipoiva { get; set; }
        public Nullable<decimal> factimporteiva { get; set; }
        public Nullable<decimal> facttotalfactura { get; set; }
        public Nullable<bool> factpara_imprimir { get; set; }
        public Nullable<bool> factimpresa { get; set; }
        public Nullable<bool> factparacontabilizar { get; set; }
        public Nullable<bool> factcontabilizada { get; set; }
        public Nullable<bool> factparadomiciliar { get; set; }
        public Nullable<bool> factdomiciliada { get; set; }
        public Nullable<decimal> facttotalremesa { get; set; }
        public Nullable<bool> factpormail { get; set; }
        public string factmail { get; set; }
    }
}
