//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BaseDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Iva
    {
        public string numerador { get;  set; }
        public string ivaconcepto { get; set; }
        public Nullable<decimal> ivaporciento { get; set; }
        public Nullable<decimal> ivarecargo { get; set; }
    }
}
