//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BaseDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ususarios
    {
        public decimal cod { get; set; }
        public Nullable<decimal> numerousuario { get; set; }
        public string nombre { get; set; }
        public string login { get; set; }
        public Nullable<bool> activo { get; set; }
        public string grupo { get; set; }
        public string pregunta { get; set; }
        public string respuesta { get; set; }
        public Nullable<bool> sistema { get; set; }
        public Nullable<bool> misdatos { get; set; }
        public Nullable<bool> usuarios { get; set; }
        public Nullable<bool> gusuarios { get; set; }
        public Nullable<bool> impuestos { get; set; }
        public Nullable<bool> rutas { get; set; }
        public Nullable<bool> clientes { get; set; }
        public Nullable<bool> gclientes { get; set; }
        public Nullable<bool> Escaner { get; set; }
        public Nullable<bool> articulos { get; set; }
        public Nullable<bool> garticulos { get; set; }
        public Nullable<bool> albaranes { get; set; }
        public Nullable<bool> galbaranes { get; set; }
        public Nullable<bool> facturas { get; set; }
        public Nullable<bool> gfacturas { get; set; }
        public Nullable<bool> csb19 { get; set; }
        public Nullable<bool> contaplus { get; set; }
        public Nullable<bool> listados { get; set; }
        public Nullable<bool> mantenimiento { get; set; }
        public Nullable<bool> copiaseguridad { get; set; }
        public Nullable<bool> agenda { get; set; }
        public Nullable<bool> avisos { get; set; }
        public Nullable<bool> gavisos { get; set; }
    }
}
