//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BaseDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ususarios
    {
        public string cod { get; set; }
        public string nombre { get; set; }
        public string login { get; set; }
        public string activo { get; set; }
        public string grupo { get; set; }
        public string pregunta { get; set; }
        public string respuesta { get; set; }
        public string sistema { get; set; }
        public string clientes { get; set; }
        public string facturas { get; set; }
        public string csb19 { get; set; }
        public string contaplus { get; set; }
        public string listados { get; set; }
        public string mantenimiento { get; set; }
        public string ayuda { get; set; }
    }
}
